export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_LOADING = 'SIGNUP_LOADING'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING'
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED'

export const GET_CATALOG_SUCCESS = 'GET_CATALOG_SUCCESS'
export const GET_CATALOG_LOADING = 'GET_CATALOG_LOADING'
export const GET_CATALOG_FAILED = 'GET_CATALOG_FAILED'
