export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_LOADING = 'SIGNUP_LOADING'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'
